 "/opt/rocm/llvm/bin/llvm-mc" -triple amdgcn-amd-amdhsa -mcpu=gfx90a -mattr=-xnack -filetype=obj -o fused.o fused.s

 "/opt/rocm/llvm/bin/lld" -flavor gnu -m elf64_amdgpu --no-undefined -shared -plugin-opt=-amdgpu-internalize-symbols -plugin-opt=mcpu=gfx90a -plugin-opt=O3 --lto-CGO3 -plugin-opt=-amdgpu-early-inline-all=true -plugin-opt=-amdgpu-function-calls=false -save-temps --whole-archive -o vectoradd_hip-hip-amdgcn-amd-amdhsa-gfx90a.out fused.o --no-whole-archive

 "/opt/rocm/llvm/bin/clang-offload-bundler" -type=o -bundle-align=4096 -targets=host-x86_64-unknown-linux,hipv4-amdgcn-amd-amdhsa--gfx90a -input=/dev/null -input=vectoradd_hip-hip-amdgcn-amd-amdhsa-gfx90a.out -output=vectoradd_hip.cpp-hip-amdgcn-amd-amdhsa.hipfb

 "/opt/rocm/llvm/bin/clang-17" -cc1 -triple x86_64-unknown-linux-gnu -aux-triple amdgcn-amd-amdhsa -E -save-temps=cwd -disable-free -clear-ast-before-backend -main-file-name vectoradd_hip.cpp -mrelocation-model static -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/whchung/projects/HIP-Examples/vectorAdd -resource-dir /opt/rocm/llvm/lib/clang/17.0.0 -internal-isystem /opt/rocm/llvm/lib/clang/17.0.0/include/cuda_wrappers -idirafter /opt/rocm/include -include __clang_hip_runtime_wrapper.h -isystem /opt/rocm/include -I /usr/include/x86_64-linux-gnu/mpich -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/x86_64-linux-gnu/c++/12 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/backward -internal-isystem /opt/rocm/llvm/lib/clang/17.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /opt/rocm/llvm/lib/clang/17.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -fdeprecated-macro -fdebug-compilation-dir=/home/whchung/projects/HIP-Examples/vectorAdd -ferror-limit 19 -fhip-new-launch-api -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -vectorize-loops -vectorize-slp -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -cuid=8d53c09c8820d487 -fcuda-allow-variadic-functions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o vectoradd_hip-host-x86_64-unknown-linux-gnu.hipi -x hip vectoradd_hip.cpp 2>/dev/null

 "/opt/rocm/llvm/bin/clang-17" -cc1 -triple x86_64-unknown-linux-gnu -aux-triple amdgcn-amd-amdhsa -emit-llvm-bc -emit-llvm-uselists -save-temps=cwd -disable-free -clear-ast-before-backend -main-file-name vectoradd_hip.cpp -mrelocation-model static -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/whchung/projects/HIP-Examples/vectorAdd -resource-dir /opt/rocm/llvm/lib/clang/17.0.0 -O3 -fdeprecated-macro -fdebug-compilation-dir=/home/whchung/projects/HIP-Examples/vectorAdd -ferror-limit 19 -fhip-new-launch-api -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -vectorize-loops -vectorize-slp -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -disable-llvm-passes -fcuda-include-gpubinary vectoradd_hip.cpp-hip-amdgcn-amd-amdhsa.hipfb -cuid=8d53c09c8820d487 -fcuda-allow-variadic-functions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o vectoradd_hip-host-x86_64-unknown-linux-gnu.bc -x hip-cpp-output vectoradd_hip-host-x86_64-unknown-linux-gnu.hipi 2>/dev/null

 "/opt/rocm/llvm/bin/clang-17" -cc1 -triple x86_64-unknown-linux-gnu -aux-triple amdgcn-amd-amdhsa -S -save-temps=cwd -disable-free -clear-ast-before-backend -main-file-name vectoradd_hip.cpp -mrelocation-model static -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/whchung/projects/HIP-Examples/vectorAdd -resource-dir /opt/rocm/llvm/lib/clang/17.0.0 -O3 -fdebug-compilation-dir=/home/whchung/projects/HIP-Examples/vectorAdd -ferror-limit 19 -fhip-new-launch-api -fgnuc-version=4.2.1 -vectorize-loops -vectorize-slp -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -cuid=8d53c09c8820d487 -fcuda-allow-variadic-functions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o vectoradd_hip-host-x86_64-unknown-linux-gnu.s -x ir vectoradd_hip-host-x86_64-unknown-linux-gnu.bc 2>/dev/null

 "/opt/rocm/llvm/bin/clang-17" -cc1as -triple x86_64-unknown-linux-gnu -filetype obj -main-file-name vectoradd_hip.cpp -target-cpu x86-64 -I /usr/include/x86_64-linux-gnu/mpich -fdebug-compilation-dir=/home/whchung/projects/HIP-Examples/vectorAdd -dwarf-version=5 -mrelocation-model static -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -o vectoradd_hip-host-x86_64-unknown-linux-gnu.o vectoradd_hip-host-x86_64-unknown-linux-gnu.s 2>/dev/null

 "/opt/rocm/llvm/bin/ld.lld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o fused.exe /lib/x86_64-linux-gnu/crt1.o /lib/x86_64-linux-gnu/crti.o /opt/rocm/llvm/lib/clang/17.0.0/lib/linux/clang_rt.crtbegin-x86_64.o -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib vectoradd_hip-host-x86_64-unknown-linux-gnu.o -lmpich -lrccl -L/opt/rocm/lib -rpath /opt/rocm/lib -lamdhip64 -lstdc++ -lm /opt/rocm/llvm/lib/clang/17.0.0/lib/linux/libclang_rt.builtins-x86_64.a -lgcc_s -lc /opt/rocm/llvm/lib/clang/17.0.0/lib/linux/libclang_rt.builtins-x86_64.a -lgcc_s /opt/rocm/llvm/lib/clang/17.0.0/lib/linux/clang_rt.crtend-x86_64.o /lib/x86_64-linux-gnu/crtn.o
